<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="DBSCAN" Version="3.0.0" />
    <PackageReference Include="NAudio" Version="2.2.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\SimTuning.Data\SimTuning.Data.csproj" />
    <ProjectReference Include="..\Spectrogram\Spectrogram.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="resources.Designer.cs">
      <DependentUpon>resources.resx</DependentUpon>
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
    </Compile>
  </ItemGroup>
  <ItemGroup>
    <EmbeddedResource Update="resources.resx">
      <LastGenOutput>resources.Designer.cs</LastGenOutput>
      <Generator>PublicResXFileCodeGenerator</Generator>
    </EmbeddedResource>
  </ItemGroup>
</Project>
