<Project>
  <!-- global configuration -->
  <PropertyGroup>
    <Copyright>Copyright (c) tuke productions</Copyright>
    <Company>tuke productions</Company>
    <Authors>Tony Meissner</Authors>
    <Owners>Tony Meissner</Owners>
    <Product>SimTuning</Product>
    <Description>Ein Tool, um Simson-Begeisterte etwas unter die Arme zu greifen und zu helfen.</Description>
    <PackageTags>c#, maui, windows, android, iOS, mac</PackageTags>
    <NeutralLanguage>de-DE</NeutralLanguage>
    <RepositoryUrl>https://github.com/tuke307/SimTuning</RepositoryUrl>
    <PackageReleaseNotes>https://github.com/tuke307/SimTuning/releases</PackageReleaseNotes>
    <RepositoryType>git</RepositoryType>
  </PropertyGroup>

  <!--  build configuration -->
  <PropertyGroup>
  <TargetFrameworks>net9.0-ios;net9.0-maccatalyst;net9.0-android</TargetFrameworks>
		<TargetFrameworks Condition="$([MSBuild]::IsOSPlatform('windows'))">$(TargetFrameworks);net9.0-windows10.0.19041.0</TargetFrameworks>
    <!-- Uncomment to also build the tizen app. You will need to install tizen by following this: https://github.com/Samsung/Tizen.NET -->
		<!-- <TargetFrameworks>$(TargetFrameworks);net9.0-tizen</TargetFrameworks> -->

		<!-- Note for MacCatalyst:
		The default runtime is maccatalyst-x64, except in Release config, in which case the default is maccatalyst-x64;maccatalyst-arm64.
		When specifying both architectures, use the plural <RuntimeIdentifiers> instead of the singular <RuntimeIdentifier>.
		The Mac App Store will NOT accept apps with ONLY maccatalyst-arm64 indicated;
		either BOTH runtimes must be indicated or ONLY macatalyst-x64. -->
		<!-- For example: <RuntimeIdentifiers>maccatalyst-x64;maccatalyst-arm64</RuntimeIdentifiers> -->
    <UseMaui>true</UseMaui>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <NoWarn>$(NoWarn);1591;1701;1702;1705;VSX1000;NU1603</NoWarn>
  </PropertyGroup>

  <!-- version configuration -->
  <PropertyGroup>
    <Version>2.0.0.0</Version>
    <AssemblyVersion>2.0.0.0</AssemblyVersion>
    <FileVersion>2.0.0.0</FileVersion>
  </PropertyGroup>

  <!-- release configuration -->
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
  </PropertyGroup>

  <!-- debug configuration -->
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CodeAnalysisRuleSet>$(MSBuildThisFileDirectory)/Code Rules.ruleset</CodeAnalysisRuleSet>
  </PropertyGroup>


  <!-- Nuget configuration -->
  <ItemGroup>
    <!-- Nugets -->
    <PackageReference Include="Microsoft.Maui.Controls" Version="9.0.10" />
		<PackageReference Include="Microsoft.Maui.Controls.Compatibility" Version="9.0.10" />
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.3.2" />
    <PackageReference Include="UnitsNet" Version="5.60.0" />
    <PackageReference Include="CommunityToolkit.Maui" Version="9.1.1" />
    <PackageReference Include="CommunityToolkit.Maui.MediaElement" Version="4.1.0" />
    <PackageReference Include="Sharpnado.Maui.TaskLoaderView" Version="2.5.1" />
    <PackageReference Include="Sharpnado.Tabs.Maui" Version="3.2.1" />
    <PackageReference Include="LiveChartsCore.SkiaSharpView.Maui" Version="2.0.0-rc4.5" />
    <PackageReference Include="SkiaSharp" Version="2.88.9" />
    <PackageReference Include="MathNet.Numerics" Version="5.0.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
    <PackageReference Include="Serilog" Version="4.1.0" />
    <PackageReference Include="Serilog.Sinks.File" Version="6.0.0" />
    <PackageReference Include="Serilog.Sinks.Debug" Version="3.0.0" />
    <PackageReference Include="Serilog.Extensions.Logging" Version="8.0.0" />
    <PackageReference Include="CommunityToolkit.WinUI.Notifications" Version="7.1.2" />

    <!-- Analyzers -->
    <PackageReference Include="AsyncFixer" Version="1.6.0" PrivateAssets="All" />

    <PackageReference Include="StyleCop.Analyzers" Version="1.1.118">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>