<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<SingleProject>True</SingleProject>
		<RootNamespace>SimTuning.Maui.App</RootNamespace>

		<!-- Display name -->
		<ApplicationTitle>SimTuning</ApplicationTitle>

		<!-- App Identifier -->
		<ApplicationId>com.tukeproductions.SimTuning</ApplicationId>
		<ApplicationIdGuid>1b1784dd-2ae2-443a-b0bf-43f9ef05a1ce</ApplicationIdGuid>

		<!-- Versions -->
		<ApplicationDisplayVersion>2.0</ApplicationDisplayVersion>
		<ApplicationVersion>2</ApplicationVersion>

		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">12.2</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'maccatalyst'">15.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">21.0</SupportedOSPlatformVersion>
		<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</SupportedOSPlatformVersion>
		<TargetPlatformMinVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'windows'">10.0.17763.0</TargetPlatformMinVersion>
		<!--<SupportedOSPlatformVersion Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'tizen'">6.5</SupportedOSPlatformVersion>-->
	</PropertyGroup>

	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net9.0-ios|AnyCPU'">
	  <CreatePackage>false</CreatePackage>
	</PropertyGroup>
	<ItemGroup>
		<!-- App Icon -->
    <MauiIcon Include="Resources\AppIcon\appicon.svg" BaseSize="1024,1024" />

    <!-- Splash Screen -->
    <MauiSplashScreen Include="Resources\Splash\splash.svg" BaseSize="1024,1024" Color="#FF303030" />

		<!-- Images -->
		<MauiImage Include="Resources\Images\*" />

		<!-- Custom Fonts -->
		<MauiFont Include="Resources\Fonts\*" />

		<!-- Raw Assets (also remove the "Resources\Raw" prefix) -->
		<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />
	</ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SimTuning.Data\SimTuning.Data.csproj" />
    <ProjectReference Include="..\SimTuning.Core\SimTuning.Core.csproj" />
    <ProjectReference Include="..\SimTuning.Maui.UI\SimTuning.Maui.UI.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\Images\" />
    <Folder Include="Resources\Styles\" />
  </ItemGroup>
</Project>

